### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by dashed** [iofjuupasli/combine-section-selectors#1]
This module is pretty slick. 👍 

I'm wondering if you are in the midst of adding tests?

**Comment by iofjuupasli** [comment]
:+1: 
Yes, I'll add tests soon

**Comment by iofjuupasli** [comment]
https://github.com/iofjuupasli/combine-section-selectors/commit/e8424a35bb8e906c156ae5bd7452b8b942ef5db6

**Comment by dashed** [comment]
@iofjuupasli wow fast! 👍
